[package]
name = "otherlib"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
koto = "0.16.0"

[lints]
workspace = true
